[theme]
base = "dark"
primaryColor = "#00BFFF"
backgroundColor = "#474747ff"           # خلفية فاتحة يدويًا
secondaryBackgroundColor = "#7397c2da"
textColor = "#ffffffff"                 # خط أبيض
font = "sans serif"
