[theme]
base = "dark"
primaryColor = "#00BFFF"
backgroundColor = "#F0F8FF"           # خلفية فاتحة يدويًا
secondaryBackgroundColor = "#c20000ff"
textColor = "#ffffffff"                 # خط أبيض
font = "sans serif"
