[theme]
base = "dark"
primaryColor = "#00BFFF"
backgroundColor = "#F0F8FF"           # خلفية فاتحة يدويًا
secondaryBackgroundColor = "#FFFFFF"
textColor = "#FFFFFF"                 # خط أبيض
font = "sans serif"
