[theme]
base = "light"
primaryColor = "#00BFFF"              # DeepSkyBlue accent
backgroundColor = "#F0F8FF"           # AliceBlue - فاتحة ومريحة
secondaryBackgroundColor = "#FFFFFF"  # أبيض للبطاقات أو الجوانب
textColor = "#000000"                 # أسود لقراءة أوضح
font = "sans serif"
