[theme]
base = "dark"
primaryColor = "#00BFFF"
backgroundColor = "#e2989eff"           # خلفية فاتحة يدويًا
secondaryBackgroundColor = "#750404ff"
textColor = "#ffffffff"                 # خط أبيض
font = "sans serif"
